import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

import ExpenseForm from '@/components/spese/ExpenseForm';
import SidebarForm from "@/components/global/SidebarForm";

import { SidebarProvider } from "@/context/SidebarContext";
import MainContent from "@/components/MainContent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="it">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full flex flex-col md:flex-row min-h-svh bg-slate-100">
          <SidebarProvider>
            <SidebarForm>
              <ExpenseForm />
            </SidebarForm>
            <MainContent pageTitle="Test UI">
              {children}
            </MainContent>
          </SidebarProvider>
        </div>
        <footer className="text-center p-4 w-full bg-slate-200 text-slate-600 border-t border-slate-300">
          <p>PDM Power by OpenCom - Copyright © 2014-2025</p>
        </footer>
      </body>
    </html>
  );
}
