import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Logo from "@/app/components/brand/Logo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <section className="max-w-7xl p-2 mx-auto flex flex-row items-center gap-2 justify-between">
            <Logo />
            <nav>
              <ul className="flex flex-row list-none gap-4 text-sm text-slate-600 *:hover:underline">
                <li>Menu</li>
                <li>Profilo</li>
                <li>Impostazioni</li>
              </ul>
            </nav>
          </section>
          <section className="p-1 py-2 border-y border-slate-200 bg-slate-50">
            <div className="max-w-7xl mx-auto flex flex-row items-center gap-2 justify-between font-semibold text-slate-700 font-[family-name:var(--font-geist-mono)]">
              <h1>TITOLO PAGINA</h1>
            </div>
          </section>
        </header>
        <main className="w-full h-full bg-slate-100">{children}</main>
        <footer className="text-center p-4 w-full bg-slate-200 text-slate-600 border-t border-slate-300">
          <p>PDM Power by OpenCom - Copyright © 2014-2025</p>
        </footer>
      </body>
    </html>
  );
}
